on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: chmod +x build.sh
        run: chmod +x .github/scripts/build.sh
      - name: Build the project
        run: .github/scripts/build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          path: build/*
