on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Install dependencies
        run: go mod tidy
      - name: chmod +x build.sh
        run: chmod +x .github/scripts/build.sh
      - name: Build the project
        run: .github/scripts/build.sh
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v5
        with:
          name: mcsm-win64.exe
          path: build/mcsm-win64.exe
      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v5
        with:
          name: mcsm-linux
          path: build/mcsm-linux
      - name: Upload macOS arm build artifact
        uses: actions/upload-artifact@v5
        with:
          name: mcsm-macos-arm64
          path: build/mcsm-osx-arm
      - name: Upload macOS x64 build artifact
        uses: actions/upload-artifact@v5
        with:
          name: mcsm-macos-x64
          path: build/mcsm-osx-x64
